version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...
    - go run ./cmd profile benchmark --generate 1000 --iterations 3

builds:
  - main: ./cmd
    binary: mdnotes
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/eoinhurrell/mdnotes:{{ .Version }}-amd64"
      - "ghcr.io/eoinhurrell/mdnotes:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/eoinhurrell/mdnotes:{{ .Version }}-arm64v8"
      - "ghcr.io/eoinhurrell/mdnotes:latest-arm64v8"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/eoinhurrell/mdnotes:{{ .Version }}"
    image_templates:
      - "ghcr.io/eoinhurrell/mdnotes:{{ .Version }}-amd64"
      - "ghcr.io/eoinhurrell/mdnotes:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/eoinhurrell/mdnotes:latest"
    image_templates:
      - "ghcr.io/eoinhurrell/mdnotes:latest-amd64"
      - "ghcr.io/eoinhurrell/mdnotes:latest-arm64v8"

brews:
  - repository:
      owner: eoinhurrell
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/eoinhurrell/mdnotes"
    description: "A powerful CLI tool for managing Obsidian markdown note vaults"
    license: "MIT"
    test: |
      system "#{bin}/mdnotes --version"
    install: |
      bin.install "mdnotes"
      man1.install "docs/mdnotes.1" if File.exist? "docs/mdnotes.1"

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://github.com/eoinhurrell/mdnotes
    description: |-
      A powerful CLI tool for managing Obsidian markdown note vaults with 
      automated batch operations, frontmatter management, and external service integrations.
    maintainer: Eoin Hurrell <eoin.hurrell@gmail.com>
    license: MIT
    vendor: Eoin Hurrell
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/mdnotes/copyright
        file_info:
          mode: 0644
      - src: ./docs/USER_GUIDE.md
        dst: /usr/share/doc/mdnotes/USER_GUIDE.md
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - termux.deb # Termux
      - archlinux # Arch Linux
    dependencies:
      - git
    recommends:
      - obsidian

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/eoinhurrell/

release:
  footer: |
    ## Installation

    ### Download
    Download the pre-compiled binaries from the [releases page](https://github.com/eoinhurrell/mdnotes/releases) and copy to the desired location.

    ### Homebrew
    ```bash
    brew install eoinhurrell/tap/mdnotes
    ```

    ### Go Install
    ```bash
    go install github.com/eoinhurrell/mdnotes/cmd@latest
    ```

    ### Docker
    ```bash
    docker run --rm -v $(pwd):/vault ghcr.io/eoinhurrell/mdnotes:latest analyze stats /vault
    ```

    ## Checksums
    The checksums are computed with sha256sum and can be checked with:
    ```bash
    sha256sum -c checksums.txt
    ```

  extra_files:
    - glob: ./docs/*.md

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"