name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ubuntu-latest-go-1.24-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ubuntu-latest-go-1.24-
          ubuntu-latest-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -coverprofile=coverage.out ./...

    - name: Build binary
      run: go build -v -o mdnotes ./cmd

    - name: Test basic functionality
      run: |
        ./mdnotes --version
        ./mdnotes --help

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m --config=.golangci.yml